name: GitHub Task Workflow
on:
  pull_request:
    branches:
      - '*'

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: true
      
    steps:
      - name: Display GITHUB_ACTIONS environment variable
        run: echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
      
      - name: Show branch and repository information
        run: |
          echo "Current branch: $GITHUB_REF"
          echo "Repository: $GITHUB_REPOSITORY"
      
      - name: Show triggering event
        run: echo "Triggered by $GITHUB_EVENT_NAME event"
